parameters:
    database_host: localhost
    database_port: 3306
    database_name: tp
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 4051054865084cb6352c2517e64b344701b5e013

